;
; File generated by cc65 v 2.17 - Git 6c320f7d
;
	.fopt		compiler,"cc65 v 2.17 - Git 6c320f7d"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_lfill
	.export		_rectangle
	.export		_panel

; ---------------------------------------------------------------
; void __near__ rectangle (const unsigned char, const unsigned char, const unsigned char, const unsigned char, const unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rectangle: near

.segment	"CODE"

	jsr     pusha
	ldy     #$0A
	jsr     subysp
	ldx     #$00
	ldy     #$0C
	lda     (sp),y
	ldy     #$0E
	ora     (sp),y
	and     #$80
	jne     L0107
	ldy     #$0B
	lda     (sp),y
	ldy     #$0D
	ora     (sp),y
	and     #$80
	jne     L0107
	dey
	lda     (sp),y
	cmp     #$40
	jcs     L0107
	dey
	lda     (sp),y
	cmp     #$1E
	jcs     L0107
	iny
	lda     (sp),y
	clc
	ldy     #$0E
	adc     (sp),y
	bcc     L01C7
	inx
L01C7:	cmp     #$40
	txa
	sbc     #$00
	jcs     L0107
	ldx     #$00
	ldy     #$0B
	lda     (sp),y
	clc
	ldy     #$0D
	adc     (sp),y
	bcc     L01C8
	inx
L01C8:	cmp     #$1E
	txa
	sbc     #$00
	jcs     L0107
	ldx     #$00
	lda     (sp),y
	jsr     aslax4
	jsr     aslax2
	ldy     #$06
	jsr     staxysp
	ldy     #$0E
	lda     (sp),y
	ldx     #$00
	ldy     #$06
	jsr     addeqysp
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	pha
	txa
	clc
	adc     #$F4
	tax
	pla
	ldy     #$04
	jsr     staxysp
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     push0ax
	ldx     #$00
	lda     #$F8
	sta     sreg
	lda     #$0F
	sta     sreg+1
	txa
	jsr     tosaddeax
	jsr     steax0sp
	jsr     decsp5
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	stz     sreg
	stz     sreg+1
	ldy     #$01
	jsr     steaxysp
	lda     #$85
	sta     (sp)
	ldy     #$11
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$83
	sta     (ptr1)
	ldy     #$0C
	lda     (sp),y
	clc
	ldy     #$04
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	sec
	sbc     #$01
	bcs     L012E
	dex
L012E:	sta     ptr1
	stx     ptr1+1
	lda     #$84
	sta     (ptr1)
	jsr     decsp5
	ldy     #$08
	jsr     ldeaxysp
	ldy     #$01
	jsr     steaxysp
	ldy     #$0F
	lda     (sp),y
	sta     (sp)
	ldy     #$11
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
	ldy     #$04
	ldx     #$00
	lda     #$40
	jsr     addeqysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$40
	jsr     laddeq0sp
	lda     #$02
	ldy     #$09
L01CB:	sta     (sp),y
	ldy     #$0B
	cmp     (sp),y
	jcs     L0139
	jsr     decsp5
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	stz     sreg
	stz     sreg+1
	ldy     #$01
	jsr     steaxysp
	lda     #$20
	sta     (sp)
	ldy     #$11
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$80
	sta     (ptr1)
	ldy     #$0C
	lda     (sp),y
	clc
	ldy     #$04
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	sec
	sbc     #$01
	bcs     L014B
	dex
L014B:	sta     ptr1
	stx     ptr1+1
	lda     #$80
	sta     (ptr1)
	jsr     decsp5
	ldy     #$08
	jsr     ldeaxysp
	ldy     #$01
	jsr     steaxysp
	ldy     #$0F
	lda     (sp),y
	sta     (sp)
	ldx     #$00
	lda     #$01
	jsr     _lfill
	jsr     decsp5
	ldy     #$08
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	ldx     #$00
	lda     (sp),y
	jsr     tosadd0ax
	ldy     #$01
	jsr     deceaxy
	jsr     steaxysp
	ldy     #$0F
	lda     (sp),y
	sta     (sp)
	ldx     #$00
	lda     #$01
	jsr     _lfill
	ldy     #$04
	ldx     #$00
	lda     #$40
	jsr     addeqysp
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$40
	jsr     laddeq0sp
	ldy     #$09
	lda     (sp),y
	ina
	jmp     L01CB
L0139:	jsr     decsp5
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	stz     sreg
	stz     sreg+1
	ldy     #$01
	jsr     steaxysp
	lda     #$85
	sta     (sp)
	ldy     #$11
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     #$81
	sta     (ptr1)
	ldy     #$0C
	lda     (sp),y
	clc
	ldy     #$04
	adc     (sp),y
	pha
	lda     #$00
	iny
	adc     (sp),y
	tax
	pla
	sec
	sbc     #$01
	bcs     L0164
	dex
L0164:	sta     ptr1
	stx     ptr1+1
	lda     #$82
	sta     (ptr1)
	jsr     decsp5
	ldy     #$08
	jsr     ldeaxysp
	ldy     #$01
	jsr     steaxysp
	ldy     #$0F
	lda     (sp),y
	sta     (sp)
	ldy     #$11
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
L0107:	ldy     #$0F
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ panel (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_panel: near

.segment	"CODE"

	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     decsp2
	ldx     #$00
	ldy     #$07
	lda     (sp),y
	ldy     #$09
	ora     (sp),y
	and     #$80
	jne     L016B
	ldy     #$06
	lda     (sp),y
	ldy     #$08
	ora     (sp),y
	and     #$80
	jne     L016B
	dey
	lda     (sp),y
	cmp     #$40
	jcs     L016B
	dey
	lda     (sp),y
	cmp     #$1E
	jcs     L016B
	iny
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	bcc     L01CC
	inx
L01CC:	cmp     #$40
	txa
	sbc     #$00
	jcs     L016B
	ldx     #$00
	ldy     #$06
	lda     (sp),y
	clc
	ldy     #$08
	adc     (sp),y
	bcc     L01CD
	inx
L01CD:	cmp     #$1E
	txa
	sbc     #$00
	jcs     L016B
	jsr     decsp4
	ldy     #$0D
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	ldy     #$0C
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	sta     (sp)
	ldy     #$07
	lda     (sp),y
	jsr     _rectangle
	bra     L0185
L0183:	ldy     #$02
	lda     (sp),y
	ina
	sta     (sp),y
L0185:	ldy     #$05
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$02
	lda     (sp),y
	tay
	lda     (ptr1),y
	beq     L01D4
	ldy     #$02
	lda     (sp),y
	ldy     #$07
	cmp     (sp),y
	bcc     L0183
	bra     L01DA
L01D4:	ldy     #$07
L01DA:	lda     (sp),y
	sec
	ldy     #$02
	sbc     (sp),y
	ldx     #$00
	ina
	bne     L018E
	inx
L018E:	jsr     shrax1
	clc
	ldy     #$09
	adc     (sp),y
	sta     (sp)
	lda     #$00
	ldy     #$01
	sta     (sp),y
	jsr     decsp5
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     push0ax
	lda     #$F8
	sta     sreg
	lda     #$0F
	sta     sreg+1
	txa
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$11
	ldx     #$00
	lda     (sp),y
	ina
	bne     L0195
	inx
L0195:	jsr     shlax4
	jsr     shlax2
	jsr     tosadd0ax
	ldy     #$01
	jsr     steaxysp
	lda     #$01
	sta     (sp)
	ldy     #$07
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
	lda     #$00
	ldy     #$01
	sta     (sp),y
	tax
L01D9:	lda     (sp),y
	iny
	cmp     (sp),y
	bcs     L0199
	dey
	lda     (sp),y
	sta     ptr1
	txa
	clc
	adc     #$F4
	sta     ptr1+1
	lda     (sp)
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01CE
	inx
L01CE:	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$08
	lda     (sp),y
	ina
	bne     L01A5
	inx
L01A5:	jsr     shlax4
	jsr     shlax2
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ina
	sta     (sp),y
	bra     L01D9
L0199:	jsr     decsp5
	ldy     #$0D
	lda     (sp),y
	clc
	adc     #$02
	bcc     L01AC
	inx
L01AC:	jsr     shlax4
	jsr     shlax2
	sta     ptr1
	txa
	clc
	adc     #$F4
	sta     ptr1+1
	iny
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01CF
	inx
L01CF:	ina
	bne     L01AD
	inx
L01AD:	stz     sreg
	stz     sreg+1
	ldy     #$01
	jsr     steaxysp
	lda     #$85
	sta     (sp)
	ldy     #$0C
	ldx     #$00
	lda     (sp),y
	sec
	sbc     #$02
	bcs     L01B0
	dex
L01B0:	jsr     _lfill
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$02
	bcc     L01B6
	inx
L01B6:	jsr     shlax4
	jsr     shlax2
	sta     ptr1
	txa
	clc
	adc     #$F4
	sta     ptr1+1
	iny
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01D0
	inx
L01D0:	sta     ptr1
	stx     ptr1+1
	lda     #$86
	sta     (ptr1)
	dey
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$02
	bcc     L01BD
	inx
L01BD:	jsr     shlax4
	jsr     shlax2
	sta     ptr1
	txa
	clc
	adc     #$F4
	sta     ptr1+1
	iny
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01D1
	inx
L01D1:	sta     ptr1
	stx     ptr1+1
	ldy     #$07
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L01D2
	inx
L01D2:	sec
	sbc     #$01
	bcs     L01BE
	dex
L01BE:	sta     ptr1
	stx     ptr1+1
	lda     #$87
	sta     (ptr1)
	jsr     decsp5
	ldy     #$0D
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$02
	bcc     L01C4
	inx
L01C4:	jsr     shlax4
	jsr     shlax2
	jsr     push0ax
	ldx     #$00
	lda     #$F8
	sta     sreg
	lda     #$0F
	sta     sreg+1
	txa
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$12
	ldx     #$00
	lda     (sp),y
	jsr     tosadd0ax
	ldy     #$01
	jsr     steaxysp
	ldy     #$08
	lda     (sp),y
	sta     (sp)
	ldy     #$0C
	lda     (sp),y
	ldx     #$00
	jsr     _lfill
L016B:	ldy     #$0A
	jmp     addysp

.endproc

