;
; File generated by cc65 v 2.17 - Git 6c320f7d
;
	.fopt		compiler,"cc65 v 2.17 - Git 6c320f7d"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_mega65_fast
	.export		_sdhc_card
	.export		_prop_m65u_name
	.export		_usleep

.segment	"DATA"

_sdhc_card:
	.byte	$00
_prop_m65u_name:
	.addr	L0105

.segment	"RODATA"

L0105:
	.byte	$50,$52,$4F,$50,$2E,$4D,$36,$35,$55,$2E,$4E,$41,$4D,$45,$3D,$53
	.byte	$44,$43,$41,$52,$44,$20,$46,$44,$49,$53,$4B,$2B,$46,$4F,$52,$4D
	.byte	$41,$54,$20,$55,$54,$49,$4C,$49,$54,$59,$00

; ---------------------------------------------------------------
; void __near__ mega65_fast (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mega65_fast: near

.segment	"CODE"

	lda     #$41
	sta     $0000
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ usleep (unsigned long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_usleep: near

.segment	"CODE"

	jsr     pusheax
	bra     L010A
L011D:	lda     $D012
	jsr     pusha
	ldy     #$00
L011E:	lda     (sp),y
	cmp     $D012
	beq     L011E
	ldx     #$00
	stz     sreg
	stz     sreg+1
	lda     #$40
	ldy     #$01
	jsr     lsubeqysp
	jsr     incsp1
L010A:	jsr     ldeax0sp
	cmp     #$41
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L011D
	jmp     incsp4

.endproc

