;
; File generated by cc65 v 2.17 - Git 6c320f7d
;
	.fopt		compiler,"cc65 v 2.17 - Git 6c320f7d"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_gotoxy
	.import		_cgetc
	.import		_textcolor
	.import		_printf
	.import		_rectangle
	.import		_panel
	.import		_lfill
	.export		_clearNumero
	.export		_layout

.segment	"RODATA"

L0076:
	.byte	$D3,$CD,$D3,$3A,$20,$C3,$4F,$4E,$54,$41,$43,$54,$20,$4E,$41,$4D
	.byte	$45,$00
L0087:
	.byte	$C1,$44,$44,$2F,$C5,$44,$49,$54,$20,$43,$4F,$4E,$54,$41,$43,$54
	.byte	$00
L000D:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$00
L005E:
	.byte	$C9,$4E,$43,$4F,$4D,$49,$4E,$47,$20,$43,$41,$4C,$4C,$00
L001B:
	.byte	$C3,$4F,$4E,$54,$41,$43,$54,$53,$00
L00AE:
	.byte	$C3,$4F,$4E,$46,$49,$52,$4D,$00
L0096:
	.byte	$CE,$55,$4D,$42,$45,$52,$00
L00BF:
	.byte	$C4,$45,$4C,$45,$54,$45,$00
L009C:
	.byte	$CD,$41,$49,$4C,$00
L0090:
	.byte	$CE,$41,$4D,$45,$00
L006D:
	.byte	$C5,$4E,$44,$00
L007D:
	.byte	$25,$44,$00

; ---------------------------------------------------------------
; unsigned char __near__ clearNumero (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clearNumero: near

.segment	"CODE"

	lda     #$01
	jsr     pusha
	lda     #$03
	jsr     _gotoxy
	lda     #<(L000D)
	ldx     #>(L000D)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	txa
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ layout (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_layout: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp3
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	cmp     #$01
	beq     L0015
	cmp     #$02
	jeq     L0058
	cmp     #$03
	jeq     L0070
	cmp     #$04
	jeq     L0081
	jmp     L00C6
L0015:	jsr     decsp6
	lda     #$1A
	ldy     #$05
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	dea
	dey
	sta     (sp),y
	lda     #<(L001B)
	sta     (sp)
	dey
	lda     #>(L001B)
	sta     (sp),y
	lda     #$0F
	jsr     _panel
	jsr     decsp4
	lda     #$00
	ldy     #$03
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$19
	dey
	sta     (sp),y
	lda     #$03
	sta     (sp)
	lda     #$06
	jsr     _rectangle
	lda     #$00
	ldy     #$02
	sta     (sp),y
	tax
L00C5:	lda     (sp),y
	cmp     #$09
	jcs     L00C6
	jsr     pusha0
	lda     #$03
	jsr     tosudiva0
	cpx     #$00
	bne     L002C
	cmp     #$00
	bne     L002C
	lda     #$05
	bra     L00C7
L002C:	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$03
	jsr     tosudiva0
	cpx     #$00
	bne     L0032
	cmp     #$01
	bne     L0032
	lda     #$0A
	bra     L00C7
L0032:	lda     #$0F
L00C7:	sta     (sp)
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     #$03
	jsr     tosumoda0
	jsr     mulax5
	ldy     #$01
	sta     (sp),y
	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	ldy     #$03
	sta     (sp),y
	iny
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	lda     #$05
	dey
	sta     (sp),y
	sta     (sp)
	ina
	jsr     _rectangle
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0048
	inx
L0048:	sta     ptr1
	txa
	clc
	adc     #$F4
	sta     ptr1+1
	ldx     #$00
	lda     (sp)
	clc
	adc     #$02
	bcc     L004A
	inx
L004A:	jsr     shlax4
	jsr     shlax2
	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	iny
	lda     (sp),y
	ina
	clc
	adc     #$30
	sta     (ptr1)
	jsr     decsp5
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0052
	inx
L0052:	jsr     push0ax
	ldx     #$00
	lda     #$F8
	sta     sreg
	lda     #$0F
	sta     sreg+1
	txa
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0054
	inx
L0054:	jsr     shlax4
	jsr     shlax2
	jsr     tosadd0ax
	ldy     #$01
	jsr     steaxysp
	lda     #$01
	sta     (sp)
	ldx     #$00
	jsr     _lfill
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ina
	sta     (sp),y
	jmp     L00C5
L0058:	jsr     decsp6
	txa
	ldy     #$05
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$32
	dey
	sta     (sp),y
	lda     #$17
	dey
	sta     (sp),y
	lda     #<(L005E)
	sta     (sp)
	dey
	lda     #>(L005E)
	sta     (sp),y
	lda     #$0F
	jsr     _panel
	jsr     decsp4
	lda     #$0A
	ldy     #$03
	sta     (sp),y
	lda     #$13
	dey
	sta     (sp),y
	lda     #$1E
	dey
	sta     (sp),y
	lda     #$05
	sta     (sp)
	lda     #$02
	jsr     _rectangle
	lda     #$13
	jsr     pusha
	lda     #$15
	jsr     _gotoxy
	lda     #$02
	jsr     _textcolor
	lda     #<(L006D)
	ldx     #>(L006D)
	jmp     L00CA
L0070:	jsr     decsp6
	txa
	ldy     #$05
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$32
	dey
	sta     (sp),y
	lda     #$17
	dey
	sta     (sp),y
	lda     #<(L0076)
	sta     (sp)
	dey
	lda     #>(L0076)
	sta     (sp),y
	lda     #$0F
	jsr     _panel
	lda     #$0A
	jsr     pusha
	jsr     _gotoxy
	lda     #<(L007D)
	ldx     #>(L007D)
	jsr     pushax
	jsr     _cgetc
	jsr     pushax
	ldy     #$04
	jmp     L00C8
L0081:	jsr     decsp6
	txa
	ldy     #$05
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$32
	dey
	sta     (sp),y
	lda     #$17
	dey
	sta     (sp),y
	lda     #<(L0087)
	sta     (sp)
	dey
	lda     #>(L0087)
	sta     (sp),y
	lda     #$0F
	jsr     _panel
	lda     #$0F
	jsr     _textcolor
	lda     #$02
	jsr     pusha
	lda     #$06
	jsr     _gotoxy
	lda     #<(L0090)
	ldx     #>(L0090)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     #$02
	jsr     pusha
	lda     #$0A
	jsr     _gotoxy
	lda     #<(L0096)
	ldx     #>(L0096)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     #$02
	jsr     pusha
	lda     #$0E
	jsr     _gotoxy
	lda     #<(L009C)
	ldx     #>(L009C)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     decsp4
	lda     #$01
	ldy     #$03
	sta     (sp),y
	lda     #$13
	dey
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     #$05
	sta     (sp)
	jsr     _rectangle
	lda     #$0A
	jsr     pusha
	lda     #$15
	jsr     _gotoxy
	lda     #$05
	jsr     _textcolor
	lda     #<(L00AE)
	ldx     #>(L00AE)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     decsp4
	lda     #$19
	ldy     #$03
	sta     (sp),y
	lda     #$13
	dey
	sta     (sp),y
	lda     #$18
	dey
	sta     (sp),y
	lda     #$05
	sta     (sp)
	lda     #$02
	jsr     _rectangle
	lda     #$22
	jsr     pusha
	lda     #$15
	jsr     _gotoxy
	lda     #$02
	jsr     _textcolor
	lda     #<(L00BF)
	ldx     #>(L00BF)
L00CA:	jsr     pushax
	ldy     #$02
L00C8:	jsr     _printf
	ldx     #$00
L00C6:	txa
	jmp     incsp4

.endproc

